<?php
/*
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CalcLib\Exceptions;

use CalcLib\APIException;
use CalcLib\APIHelper;

/**
 * Is thrown when invalid input is given such as div by zero
 */
class CouldNotComputeException extends APIException
{
    /**
 * Represents the server's exception message
     * @required
     * @maps ServerMessage
     * @var string $serverMessage public property
     */
    public $serverMessage;

    /**
 * Represents the server's error code
     * @required
     * @maps ServerCode
     * @var integer $serverCode public property
     */
    public $serverCode;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
