<?php
/*
 * CalcLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CalcLib;

use CalcLib\Controllers;

/**
 * CalcLib client class
 */
class CalcClient
{
 
    /**
     * Singleton access to SimpleCalculator controller
     * @return Controllers\SimpleCalculatorController The *Singleton* instance
     */
    public function getSimpleCalculator()
    {
        return Controllers\SimpleCalculatorController::getInstance();
    }
}
